# Generated by Django 5.2.6 on 2025-09-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_movies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='due_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='late_fee',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
