# Generated by Django 5.2.6 on 2025-09-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_rentals_due_date_alter_returns_late_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentals',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='returns',
            name='late_fee',
        ),
    ]
